spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gysoft.gy@gmail.com
    password: cojn qkuh ceov rvgo
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true


mail:
  to: gysoft.gy@gmail.com